### ISSUE TITLE
Error: <TinySlider> is not a valid SSR component

### ISSUE THREAD

**Issue by MindDesign** [Mitcheljager/svelte-tiny-slider#1]
I installed the component and got this error:

`Error: <TinySlider> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled`

Is this an issue with <TinySlider> or is it not possible to use with SSR? And in that case; would it be possible to use <TinySlider> with SSR in the future? 

Thank you for your time.

**Comment by Mitcheljager** [comment]
The demo page uses SSR and it works fine, so I'm not sure why you are getting that error. What version of Svelte are you using?

**Comment by MindDesign** [comment]
Listening to the latest Svelte radio podcast where they talk about this. Will test and report back when I get a chance in a few hours.

**Comment by MindDesign** [comment]
No, removing the curlythings did not help. I am running Svelte 4.2.8 and Svelte Kit 1.27.7. Here is the complete error message:

`Error: <TinySlider> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules. Otherwise you may need to fix a <TinySlider>.`

But even if I remove SSR, it still fails, so I believe it probably is something with my config. Will try a fresh install tomorrow.

**Comment by RickRyan26** [comment]
@MindDesign Were you able to get this resolved?

**Comment by tommydesmond** [comment]
I'm getting the same error on a fresh sveltekit install too. The package.json file indicates "main" is index.d.ts which is a blank file, as is index.js. 

I'm using vite v5.0.12

├── @sveltejs/adapter-auto@3.1.1
├── @sveltejs/kit@2.5.0
├── @sveltejs/vite-plugin-svelte@3.0.2
├── svelte@4.2.9

**Comment by Mitcheljager** [comment]
This should be resolved in 1.1.2, please let me know if it works

**Comment by Mitcheljager** [comment]
This took a while to figure out, but I can confirm that I've fixed the issue in 1.1.4. Thanks!
