### ISSUE TITLE
<TinySlider> is not a valid SSR component

### ISSUE THREAD

**Issue by chandnidobariya48** [Mitcheljager/svelte-tiny-slider#3]
<TinySlider> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules. Otherwise you may need to fix a <TinySlider>.

**Comment by Mitcheljager** [comment]
This should be resolved in 1.1.2, please let me know if it works

**Comment by sadovojav** [comment]
@Mitcheljager try to disable prerender in +layout.js
I have the same error "<TinySlider> is not a valid SSR component"

**Comment by Mitcheljager** [comment]
It might be too late, but I can confirm that I've fixed the issue in 1.1.4. Thanks for the report!
